[[main]]
  identifier = "contact"
  name = "お問合わせ"
  url = "contact"
  weight = 1

[[main]]
  identifier = "about"
  name = "管理者"
  url = "about"
  weight = 2

[[main]]
  identifier = "privacy-policy"
  name = "サイトポリシー"
  url = "privacy-policy"
  weight = 3

[[main]]
  identifier = "post"
  name = "記事"
  url = "posts"
  weight = 4

[[main]]
  identifier = "archive"
  name = "アーカイブ"
  url = "archive"
  weight = 5


